"""Metadata store for the video annotation app (SQLite for dev/tests, PostgreSQL
in deployment).

The DB is the source of truth — it survives restarts and is the shared state for
concurrent annotators. Backend is selected by connection URL: a ``postgresql://``
URL uses PostgreSQL via a connection pool (multi-writer-safe); anything else is a
local SQLite file (single-writer — fine for one dev / the test suite). The
function-level API below is identical for both; the only dialect differences
(placeholders, auto-generated ids, one aggregate query) are handled internally.

Schema (intentionally minimal, multi-user-ready via ``object.created_by``):
  video       — one decoded clip configuration (name + stride + max_frames)
  object      — a tracked instance with a free-form text label (no fixed classes)
  annotation  — one object's box on one frame: OBB corners + mask polygon

Annotations carry both a rotated bounding box (``corners``, 4 points) and the
mask outline (``polygon``), so the data feeds both rotated-box and segmentation
consumers.
"""

import json
import sqlite3
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_DB_PATH = Path("outputs/annotations.db")

# Column type differences between the two backends. SQLite's INTEGER PRIMARY KEY
# is an auto-rowid; PostgreSQL uses an identity column. Everything else (TEXT,
# REAL, JSON-in-TEXT, INTEGER 0/1 flags) is shared, so the DDL is generated from
# one template.
_SCHEMA_TEMPLATE = """
CREATE TABLE IF NOT EXISTS video (
    id             {pk},
    name           TEXT NOT NULL,
    path           TEXT NOT NULL,
    width          INTEGER,
    height         INTEGER,
    fps            REAL,
    stride         INTEGER NOT NULL,
    max_frames     INTEGER,
    n_frames       INTEGER NOT NULL,
    source_indices TEXT NOT NULL,   -- JSON [orig_frame_no, ...] per decoded index
    created_at     TEXT NOT NULL,
    UNIQUE (name, stride, max_frames)
);

CREATE TABLE IF NOT EXISTS object (
    id           {pk},
    video_id     INTEGER NOT NULL REFERENCES video(id) ON DELETE CASCADE,
    label        TEXT NOT NULL,
    created_by   TEXT,
    created_at   TEXT NOT NULL,
    static       INTEGER NOT NULL DEFAULT 0,  -- 1 = tracking copies its box instead of running SAM3
    hidden       INTEGER NOT NULL DEFAULT 0,  -- 1 = overlay hidden in the UI (display only; tracking/export unaffected)
    color        TEXT                          -- hex overlay-color override, or NULL = palette default
);
CREATE INDEX IF NOT EXISTS idx_object_video ON object(video_id);

CREATE TABLE IF NOT EXISTS annotation (
    id           {pk},
    video_id     INTEGER NOT NULL REFERENCES video(id) ON DELETE CASCADE,
    object_id    INTEGER NOT NULL REFERENCES object(id) ON DELETE CASCADE,
    frame_idx    INTEGER NOT NULL,   -- decoded-frame index (matches in-memory frames)
    source_frame INTEGER,            -- original frame number in the source clip
    corners      TEXT,               -- JSON [[x,y]*4] full-res px (OBB), or NULL
    polygon      TEXT,               -- JSON [[x,y]...] outline (polygon mode only), or NULL
    mask_rle     TEXT,               -- COCO RLE at downscaled mask res — source of truth, or NULL
    score        REAL,
    origin       TEXT NOT NULL,      -- 'seed' | 'propagated' | 'manual'
    updated_at   TEXT NOT NULL,
    UNIQUE (object_id, frame_idx)
);
CREATE INDEX IF NOT EXISTS idx_annotation_video ON annotation(video_id);
"""

SCHEMA = _SCHEMA_TEMPLATE.format(pk="INTEGER PRIMARY KEY")
SCHEMA_PG = _SCHEMA_TEMPLATE.format(pk="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")


def _is_postgres_url(url: str) -> bool:
    return url.startswith(("postgres://", "postgresql://"))


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class _Conn:
    """Thin wrapper over a DB-API connection so ``db`` functions are dialect-agnostic.

    SQLite uses ``?`` placeholders; psycopg uses ``%s``. Our SQL is written with
    ``?`` and translated here for PostgreSQL (no query contains a literal ``?`` or
    ``%``, so a plain replace is safe). ``is_postgres`` lets the two functions that
    need an auto-generated id pick ``RETURNING`` vs ``lastrowid``.
    """

    def __init__(self, raw, is_postgres: bool):
        self._raw = raw
        self.is_postgres = is_postgres

    def execute(self, sql: str, params: Sequence = ()):
        if self.is_postgres:
            sql = sql.replace("?", "%s")
        return self._raw.execute(sql, params)

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


def _insert(conn: _Conn, sql: str, params: Sequence) -> int:
    """Run an INSERT and return the new row's id (dialect-aware)."""
    if conn.is_postgres:
        return conn.execute(sql + " RETURNING id", params).fetchone()["id"]
    return conn.execute(sql, params).lastrowid


def _open_sqlite(db_path: str | Path) -> _Conn:
    """Open a fresh SQLite connection with schema + migrations applied."""
    db_path = Path(db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    raw = sqlite3.connect(db_path)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA foreign_keys = ON")
    raw.execute("PRAGMA journal_mode = WAL")
    raw.executescript(SCHEMA)
    _migrate(raw)
    return _Conn(raw, is_postgres=False)


def _ensure_schema_pg(conn: _Conn) -> None:
    """Create the PostgreSQL schema (psycopg runs one statement per execute).

    Strip ``--`` line comments before splitting on ``;`` — a comment may itself
    contain a semicolon, which would otherwise cut a statement in two.
    """
    ddl = "\n".join(ln.split("--", 1)[0] for ln in SCHEMA_PG.splitlines())
    for stmt in filter(str.strip, ddl.split(";")):
        conn.execute(stmt)
    conn.commit()


def connect(db_path: str | Path = DEFAULT_DB_PATH) -> _Conn:
    """Open a single connection to the annotation DB, ensuring the schema exists.

    Used by the test suite and any single-connection caller. The app itself goes
    through :class:`Database` (a pool for PostgreSQL). A ``postgresql://`` URL
    selects PostgreSQL; anything else is treated as a SQLite path.
    """
    url = str(db_path)
    if _is_postgres_url(url):
        import psycopg
        from psycopg.rows import dict_row

        conn = _Conn(psycopg.connect(url, row_factory=dict_row), is_postgres=True)
        _ensure_schema_pg(conn)
        return conn
    return _open_sqlite(db_path)


class Database:
    """A backend handle the app builds once. Hands out short-lived connections.

    PostgreSQL uses a :class:`psycopg_pool.ConnectionPool` (per-request checkout,
    multi-writer-safe); SQLite opens a fresh connection per request. Callers use
    ``with database.connection() as c:`` for a request-scoped connection.
    """

    def __init__(self, url: str | Path = DEFAULT_DB_PATH):
        url = str(url)
        self.is_postgres = _is_postgres_url(url)
        if self.is_postgres:
            from psycopg.rows import dict_row
            from psycopg_pool import ConnectionPool

            self._pool = ConnectionPool(url, kwargs={"row_factory": dict_row}, open=True)
            with self.connection() as c:
                _ensure_schema_pg(c)
        else:
            self._pool = None
            self._path = url
            _open_sqlite(url).close()  # create the file + schema up front

    @contextmanager
    def connection(self) -> Iterator[_Conn]:
        if self.is_postgres:
            with self._pool.connection() as raw:
                yield _Conn(raw, is_postgres=True)
        else:
            conn = _open_sqlite(self._path)
            try:
                yield conn
            finally:
                conn.close()

    def close(self) -> None:
        if self._pool is not None:
            self._pool.close()


def _migrate(conn: sqlite3.Connection) -> None:
    """Bring pre-existing DBs up to the current schema."""
    have = {r["name"] for r in conn.execute("PRAGMA table_info(object)")}
    if "static" not in have:
        conn.execute("ALTER TABLE object ADD COLUMN static INTEGER NOT NULL DEFAULT 0")
    if "hidden" not in have:
        conn.execute("ALTER TABLE object ADD COLUMN hidden INTEGER NOT NULL DEFAULT 0")
    if "color" not in have:
        conn.execute("ALTER TABLE object ADD COLUMN color TEXT")
    # static used to carry a frame range; it is a plain toggle now.
    for col in ("static_start", "static_end"):
        if col in have:
            conn.execute(f"ALTER TABLE object DROP COLUMN {col}")
    ann_cols = {r["name"] for r in conn.execute("PRAGMA table_info(annotation)")}
    if "mask_rle" not in ann_cols:
        conn.execute("ALTER TABLE annotation ADD COLUMN mask_rle TEXT")
    conn.commit()


# --- videos --------------------------------------------------------------------


def upsert_video(
    conn: sqlite3.Connection,
    name: str,
    path: str,
    width: int,
    height: int,
    fps: float,
    stride: int,
    max_frames: int | None,
    n_frames: int,
    source_indices: list[int],
) -> int:
    """Return the id for this (name, stride, max_frames); insert or refresh it.

    A video row identifies one *decoding configuration*: the same clip decoded
    at a different stride is a distinct row (its frame indices differ).
    """
    # `max_frames IS ?` is not portable (PostgreSQL rejects a placeholder after
    # IS); branch on NULL instead — both dialects accept `IS NULL` / `= ?`.
    if max_frames is None:
        row = conn.execute(
            "SELECT id FROM video WHERE name = ? AND stride = ? AND max_frames IS NULL",
            (name, stride),
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT id FROM video WHERE name = ? AND stride = ? AND max_frames = ?",
            (name, stride, max_frames),
        ).fetchone()
    si = json.dumps(source_indices)
    if row:
        conn.execute(
            "UPDATE video SET path=?, width=?, height=?, fps=?, n_frames=?, source_indices=? WHERE id=?",
            (path, width, height, fps, n_frames, si, row["id"]),
        )
        conn.commit()
        return row["id"]
    vid = _insert(
        conn,
        "INSERT INTO video (name, path, width, height, fps, stride, max_frames, n_frames, "
        "source_indices, created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",
        (name, path, width, height, fps, stride, max_frames, n_frames, si, _now()),
    )
    conn.commit()
    return vid


def video_row(conn: _Conn, video_id: int):
    return conn.execute("SELECT * FROM video WHERE id = ?", (video_id,)).fetchone()


def video_by_name_stride(conn: _Conn, name: str, stride: int):
    """The video row for a (name, stride) decoding config, or None.

    Lets the app resolve a clip's ``video_id`` (for the session cache) before
    building a session. Matches the ``max_frames IS NULL`` config the app opens."""
    return conn.execute(
        "SELECT id FROM video WHERE name = ? AND stride = ? AND max_frames IS NULL",
        (name, stride),
    ).fetchone()


# --- objects -------------------------------------------------------------------


def create_object(conn: _Conn, video_id: int, label: str, created_by: str | None) -> int:
    oid = _insert(
        conn,
        "INSERT INTO object (video_id, label, created_by, created_at) VALUES (?,?,?,?)",
        (video_id, label, created_by, _now()),
    )
    conn.commit()
    return oid


def object_video_id(conn: _Conn, object_id: int) -> int | None:
    """The video an object belongs to, or None if it no longer exists.

    Lets routes that receive only an ``object_id`` (patch/delete) find the right
    cached session to update the tracker on."""
    row = conn.execute("SELECT video_id FROM object WHERE id = ?", (object_id,)).fetchone()
    return row["video_id"] if row else None


def rename_object(conn: sqlite3.Connection, object_id: int, label: str) -> None:
    conn.execute("UPDATE object SET label = ? WHERE id = ?", (label, object_id))
    conn.commit()


def set_object_static(conn: sqlite3.Connection, object_id: int, static: bool) -> None:
    """Flip an object's static flag. Static is purely a tracking-mode toggle —
    static objects get their box copied onto tracked frames instead of running
    SAM3 — so existing annotations are left untouched in both directions."""
    conn.execute(
        "UPDATE object SET static = ? WHERE id = ?", (1 if static else 0, object_id)
    )
    conn.commit()


def set_object_hidden(conn: sqlite3.Connection, object_id: int, hidden: bool) -> None:
    """Flip an object's hidden flag — a display-only toggle. Hidden objects keep
    being tracked and exported; only their overlay is suppressed in the UI."""
    conn.execute(
        "UPDATE object SET hidden = ? WHERE id = ?", (1 if hidden else 0, object_id)
    )
    conn.commit()


def set_object_color(conn: sqlite3.Connection, object_id: int, color: str | None) -> None:
    """Set (or clear, with None) an object's overlay-color override."""
    conn.execute("UPDATE object SET color = ? WHERE id = ?", (color, object_id))
    conn.commit()


def copy_nearest_annotation(
    conn: sqlite3.Connection, object_id: int, frame_idx: int, video_id: int | None = None
) -> dict | None:
    """Copy the object's box from its nearest annotated frame onto ``frame_idx``
    (origin='seed') and return the fit, or None.

    Used at track time so the selected object can start tracking from any frame.
    No-op if the object is static, has no stored box, or isn't in ``video_id``
    (when given)."""
    obj = conn.execute(
        "SELECT video_id, static FROM object WHERE id = ?", (object_id,)
    ).fetchone()
    if obj is None or obj["static"] or (video_id is not None and obj["video_id"] != video_id):
        return None
    row = conn.execute(
        "SELECT video_id, corners, polygon, mask_rle FROM annotation "
        "WHERE object_id = ? AND corners IS NOT NULL "
        "ORDER BY ABS(frame_idx - ?) LIMIT 1",
        (object_id, frame_idx),
    ).fetchone()
    if row is None:
        return None
    v = video_row(conn, row["video_id"])
    si = json.loads(v["source_indices"]) if v else []
    source_frame = si[frame_idx] if frame_idx < len(si) else None
    fit = {
        "corners": json.loads(row["corners"]),
        "polygon": json.loads(row["polygon"]) if row["polygon"] else None,
        "mask_rle": json.loads(row["mask_rle"]) if row["mask_rle"] else None,
        "score": None,
    }
    upsert_annotation(
        conn, row["video_id"], object_id, frame_idx, source_frame,
        fit["corners"], fit["polygon"], None, "seed", mask_rle=fit["mask_rle"],
    )
    return fit


def delete_object(conn: sqlite3.Connection, object_id: int) -> None:
    """Delete an object AND its annotations, for good.

    The FK is ON DELETE CASCADE, but the annotations are also deleted explicitly:
    SQLite reuses rowids, so any row that survived (e.g. a DB file predating the
    cascade, or FK enforcement off) would silently re-attach to the next created
    object."""
    conn.execute("DELETE FROM annotation WHERE object_id = ?", (object_id,))
    conn.execute("DELETE FROM object WHERE id = ?", (object_id,))
    conn.commit()


# --- annotations ---------------------------------------------------------------


def upsert_annotation(
    conn: sqlite3.Connection,
    video_id: int,
    object_id: int,
    frame_idx: int,
    source_frame: int | None,
    corners: list | None,
    polygon: list | None,
    score: float | None,
    origin: str,
    mask_rle: dict | None = None,
) -> None:
    """Insert or replace one object's annotation on one frame (keyed object+frame).

    Keyed ``UNIQUE(object_id, frame_idx)``, so two annotators editing the *same*
    object on the *same* frame is **last-writer-wins** — acceptable for a small
    shared team. Edits to different objects/frames never conflict.
    """
    conn.execute(
        "INSERT INTO annotation (video_id, object_id, frame_idx, source_frame, corners, "
        "polygon, mask_rle, score, origin, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) "
        "ON CONFLICT(object_id, frame_idx) DO UPDATE SET "
        "corners=excluded.corners, polygon=excluded.polygon, mask_rle=excluded.mask_rle, "
        "score=excluded.score, origin=excluded.origin, source_frame=excluded.source_frame, "
        "updated_at=excluded.updated_at",
        (
            video_id, object_id, frame_idx, source_frame,
            json.dumps(corners) if corners is not None else None,
            json.dumps(polygon) if polygon is not None else None,
            json.dumps(mask_rle) if mask_rle is not None else None,
            score, origin, _now(),
        ),
    )
    conn.commit()


def delete_annotation(conn: sqlite3.Connection, object_id: int, frame_idx: int) -> None:
    conn.execute(
        "DELETE FROM annotation WHERE object_id = ? AND frame_idx = ?", (object_id, frame_idx)
    )
    conn.commit()


def manual_annotations(conn: sqlite3.Connection, video_id: int) -> dict[tuple[int, int], dict]:
    """All manual annotations for a video, keyed by ``(object_id, frame_idx)``.

    Loaded once at the start of a propagation so the stream can honour manual
    precedence (never overwrite a hand-corrected box) without a per-frame query."""
    out: dict[tuple[int, int], dict] = {}
    for r in conn.execute(
        "SELECT object_id, frame_idx, corners, polygon FROM annotation "
        "WHERE video_id = ? AND origin = 'manual'",
        (video_id,),
    ):
        out[(r["object_id"], r["frame_idx"])] = {
            "corners": json.loads(r["corners"]) if r["corners"] else None,
            "polygon": json.loads(r["polygon"]) if r["polygon"] else None,
            "score": None,
        }
    return out


def seed_annotations(conn: sqlite3.Connection, video_id: int, frame_idx: int) -> dict[int, dict]:
    """Per-object annotations on one frame for non-static objects, keyed by object id.

    Used as the propagation seed set: tracking (re)starts from whatever box each
    object has on the start frame."""
    out: dict[int, dict] = {}
    for r in conn.execute(
        "SELECT a.object_id, a.corners, a.polygon, a.mask_rle FROM annotation a "
        "JOIN object o ON o.id = a.object_id "
        "WHERE a.video_id = ? AND a.frame_idx = ? AND o.static = 0",
        (video_id, frame_idx),
    ):
        if not r["corners"]:
            continue
        out[r["object_id"]] = {
            "corners": json.loads(r["corners"]),
            "polygon": json.loads(r["polygon"]) if r["polygon"] else None,
            "mask_rle": json.loads(r["mask_rle"]) if r["mask_rle"] else None,
            "score": None,
        }
    return out


def static_annotations(conn: sqlite3.Connection, video_id: int, frame_idx: int) -> dict[int, dict]:
    """Each static object's box from its annotated frame nearest ``frame_idx``,
    keyed by object id.

    Used by propagation: static objects are never passed to SAM3 — this box is
    copied onto every tracked frame instead. Objects without a stored box are
    skipped."""
    # Pick each static object's box from its frame nearest ``frame_idx``. SQLite's
    # "bare columns follow MIN()" quirk isn't portable, so use a window function
    # (works in both SQLite ≥3.25 and PostgreSQL) and keep only the nearest row.
    out: dict[int, dict] = {}
    for r in conn.execute(
        "SELECT object_id, corners, polygon, mask_rle FROM ("
        "  SELECT a.object_id, a.corners, a.polygon, a.mask_rle, "
        "    ROW_NUMBER() OVER (PARTITION BY a.object_id "
        "      ORDER BY ABS(a.frame_idx - ?), a.frame_idx) AS rn "
        "  FROM annotation a JOIN object o ON o.id = a.object_id "
        "  WHERE a.video_id = ? AND o.static = 1 AND a.corners IS NOT NULL"
        ") t WHERE rn = 1",
        (frame_idx, video_id),
    ):
        out[r["object_id"]] = {
            "corners": json.loads(r["corners"]),
            "polygon": json.loads(r["polygon"]) if r["polygon"] else None,
            "mask_rle": json.loads(r["mask_rle"]) if r["mask_rle"] else None,
            "score": None,
        }
    return out


def get_annotations(conn: sqlite3.Connection, video_id: int, include_mask: bool = False) -> dict:
    """All objects + their per-frame boxes for a video, ready to JSON-serialise.

    With ``include_mask`` each fit also carries its ``mask_rle`` (used by export; kept
    off the bulk UI payload, which fetches masks lazily via ``GET /api/mask``).

    Returns:
        {"objects": [{"id", "label", "created_by", "static", "hidden", "color"}, ...],
         "frames":  {frame_idx: {object_id:
                     {"corners", "polygon", "score", "origin", "has_mask"}}}}

    ``has_mask`` distinguishes pure bounding boxes (False — freely transformable
    in the UI) from mask-backed annotations without shipping the RLE itself.
    """
    objects = [
        {
            "id": r["id"], "label": r["label"], "created_by": r["created_by"],
            "static": bool(r["static"]), "hidden": bool(r["hidden"]), "color": r["color"],
        }
        for r in conn.execute(
            "SELECT id, label, created_by, static, hidden, color FROM object "
            "WHERE video_id = ? ORDER BY id",
            (video_id,),
        )
    ]
    cols = "object_id, frame_idx, corners, polygon, score, origin, " \
           "(mask_rle IS NOT NULL) AS has_mask"
    if include_mask:
        cols += ", mask_rle"
    frames: dict[int, dict[int, dict]] = {}
    for r in conn.execute(
        f"SELECT {cols} FROM annotation WHERE video_id = ? ORDER BY frame_idx",
        (video_id,),
    ):
        fit = {
            "corners": json.loads(r["corners"]) if r["corners"] else None,
            "polygon": json.loads(r["polygon"]) if r["polygon"] else None,
            "score": r["score"],
            "origin": r["origin"],
            "has_mask": bool(r["has_mask"]),
        }
        if include_mask:
            fit["mask_rle"] = json.loads(r["mask_rle"]) if r["mask_rle"] else None
        frames.setdefault(r["frame_idx"], {})[r["object_id"]] = fit
    return {"objects": objects, "frames": frames}


def annotation_status(conn: _Conn) -> dict:
    """Per-clip-name annotation summary for the hub gallery.

    Joins ``video ⋈ object`` and aggregates by clip name. One clip name can have
    several ``video`` rows (different strides), so grouping is by ``video.name``
    across all of them. Only names with ≥1 object appear — absence = unlabeled.

    Returns ``{"<name>": {"annotators": [...], "object_count": N, "last_activity": iso}}``.
    """
    # ponytail: aggregate in Python — DISTINCT-into-array differs across sqlite/pg
    # (array_agg vs group_concat), and object counts here are tiny.
    agg: dict[str, dict] = {}
    for r in conn.execute(
        "SELECT v.name AS name, o.created_by AS created_by, o.created_at AS created_at "
        "FROM video v JOIN object o ON o.video_id = v.id"
    ):
        e = agg.setdefault(
            r["name"], {"annotators": set(), "object_count": 0, "last_activity": None}
        )
        e["object_count"] += 1
        if r["created_by"]:
            e["annotators"].add(r["created_by"])
        # created_at is ISO-8601 → lexical max == chronological max.
        if r["created_at"] and (e["last_activity"] is None or r["created_at"] > e["last_activity"]):
            e["last_activity"] = r["created_at"]
    return {
        name: {
            "annotators": sorted(e["annotators"]),
            "object_count": e["object_count"],
            "last_activity": e["last_activity"],
        }
        for name, e in agg.items()
    }


def get_annotation_mask(
    conn: sqlite3.Connection, video_id: int, object_id: int, frame_idx: int
) -> dict | None:
    """One annotation's mask source for the overlay fetch: ``{"mask_rle", "polygon"}``.

    Returns None if the annotation does not exist; either field may be None (old rows
    have only a polygon, brush-mode rows have only a mask)."""
    r = conn.execute(
        "SELECT mask_rle, polygon FROM annotation "
        "WHERE video_id = ? AND object_id = ? AND frame_idx = ?",
        (video_id, object_id, frame_idx),
    ).fetchone()
    if r is None:
        return None
    return {
        "mask_rle": json.loads(r["mask_rle"]) if r["mask_rle"] else None,
        "polygon": json.loads(r["polygon"]) if r["polygon"] else None,
    }
